# Generated by Django 4.2.11 on 2024-04-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('item_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('availability', models.IntegerField(default=0)),
                ('in_use', models.IntegerField(default=0)),
            ],
        ),
    ]
