# Generated by Django 4.2.11 on 2024-04-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_inventoryitem_secondary_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='secondary_name',
        ),
    ]
