# Generated by Django 4.2.11 on 2024-04-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0003_remove_inventoryitem_secondary_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='secondary_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
